(define t_iter 0)
(define prev '())
(define curr '())

(define (check-swap-buffers t)
  (if (not (equal? t t_iter))
    (begin
      (set! prev curr)
      (set! curr '())
      (set! t_iter t))))

(When ((?p (region parameter) ?r)
       (?r (region points) (?ulhc ?urhc ?llhc ?lrhc)))
 do (let* ((diagonal (vec-from-to ?ulhc ?lrhc))
           (center (vec->ints (vec-add ?ulhc (vec-mul diagonal 0.5)))))
       (Claim ?r '(region center) center)))

(When ((this (page points) (?ulhc ?urhc ?llhc ?lrhc))
       (?r (region name) parameter)
       (?r (region center) ?c)
       (time now ?t))
 do (let* ((diagonal (vec-from-to ?ulhc ?lrhc))
           (center (vec->ints (vec-add ?ulhc (vec-mul diagonal 0.5))))
           (d (vec-length (vec-from-to center ?c))))
      (check-swap-buffers ?t)
      (if (null? curr)
        (set! curr (cons d ?r))
        (let ((mind (car curr)))
          (if (< d mind) (set! curr (cons d ?r)))))))

(When ((time now ?t)) do
  (check-swap-buffers ?t)
  (if (not (null? prev))
    (let ((regionid (cdr prev)))
      (Claim this 'adjusts regionid))))

; TODO: cycle through min-max range with modulo, based on rotation
(When ((this adjusts ?r)
       (?p (region parameter) ?r)
       (?r (region parameter) ?paramid)
       (?paramid (parameter name) ?name)
       (?paramid (parameter min) ?min)
       (?paramid (parameter max) ?max)
       (?paramid (parameter default) ?default)
       (this (page rotation) ?rotation))
 do (Remember ?p ?p ?name ?rotation))
