(Claim this 'hand 'left)

(When ((?p hand right)
       (this (page points) (?ulhc ?urhc ?llhc ?lrhc))
       (?p (page points) (?pulhc ?purhc ?pllhc ?plrhc)))
 do (let* ((left-mid (vec-add ?ulhc (vec-mul (vec-from-to ?lrhc ?ulhc) (/ 2 5))))
           (left-midx (inexact->exact (round (car left-mid)))) (left-midy (inexact->exact (round (cdr left-mid))))
           (right-mid (vec-add ?pulhc (vec-mul (vec-from-to ?plrhc ?pulhc) (/ 2 5))))
           (right-midx (inexact->exact (round (car right-mid)))) (right-midy (inexact->exact (round (cdr right-mid)))) )
      (draw-rectangle projection left-midx left-midy right-midx right-midy 255 255 255 2)
      (Claim (gensym) 'selection-rect (cons (cons left-midx left-midy) (cons right-midx right-midy)))))

(When ((this (page points) (?ulhc ?urhc ?llhc ?lrhc)))
 do (Wish this 'has-region-from-tag-unrotated
     `(snapshot 1.2 0 4.2 0 1.2 3 4.2 3)))

(When ((?id selection-rect (?p . ?q))
       (this (region snapshot) (?rotation ?ulhc ?urhc ?llhc ?lrhc)))
 do (let ((proj-pts (bytevector->pointer (points->bytevector ?p ?q)))
          (out-pts (bytevector->pointer (make-bytevector (* 8 2)))))
      (perspective-transform proj-pts 2 projection->webcam out-pts)
      (let* ((webcam-rect (bounding-rect out-pts 2))
             (webcam-roi (region-from-rect webcam webcam-rect)))
        (draw-mat-onto-region-opaque webcam-roi projection ?rotation ?ulhc ?lrhc)
        (free-image webcam-roi)
        (free-rectangle webcam-rect))))
