; claim a relative region based on detected tag dimensions
; x and y are scaling factors with base equal to tags inner box vectors
; dist scales with same vector, but is distance from the tag center
(When ((?someone wishes (?p has-region-right (?region ?x ?y ?dist)))
       (?p (page points) (?ulhc ?urhc ?llhc ?lrhc)))
 do (let* ((dx-vec (vec-from-to ?ulhc ?urhc))
           (dy-vec (vec-from-to ?ulhc ?llhc))
           (dx (/ ?x 2.0)) (dy (/ ?y 2.0))
           (diagonal (vec-from-to ?ulhc ?lrhc))
           (mid (vec-add ?ulhc (vec-mul diagonal 0.5)))
           (mid-right (vec-add mid (vec-mul dx-vec (+ 1 ?dist))))
           (ulhc (vec-add mid-right (vec-mul dy-vec (- dy))))
           (llhc (vec-add mid-right (vec-mul dy-vec dy)))
           (urhc (vec-add ulhc (vec-mul dx-vec ?x)))
           (lrhc (vec-add llhc (vec-mul dx-vec ?x)))
           (region (map vec->ints (list ulhc urhc llhc lrhc))))
       (Claim ?p 'has-region (cons ?region region))))

(When ((?someone wishes (?p has-region-left (?region ?x ?y ?dist)))
       (?p (page points) (?ulhc ?urhc ?llhc ?lrhc)))
 do (let* ((dx-vec (vec-from-to ?urhc ?ulhc))
           (dy-vec (vec-from-to ?ulhc ?llhc))
           (dx (/ ?x 2.0)) (dy (/ ?y 2.0))
           (diagonal (vec-from-to ?ulhc ?lrhc))
           (mid (vec-add ?ulhc (vec-mul diagonal 0.5)))
           (mid-left (vec-add mid (vec-mul dx-vec (+ 1 ?dist))))
           (urhc (vec-add mid-left (vec-mul dy-vec (- dy))))
           (lrhc (vec-add mid-left (vec-mul dy-vec dy)))
           (ulhc (vec-add urhc (vec-mul dx-vec ?x)))
           (llhc (vec-add lrhc (vec-mul dx-vec ?x)))
           (region (map vec->ints (list ulhc urhc llhc lrhc))))
       (Claim ?p 'has-region (cons ?region region))))

(When ((?someone wishes (?p has-region-up (?region ?x ?y ?dist)))
       (?p (page points) (?ulhc ?urhc ?llhc ?lrhc)))
 do (let* ((dx-vec (vec-from-to ?ulhc ?urhc))
           (dy-vec (vec-from-to ?llhc ?ulhc))
           (dx (/ ?x 2.0)) (dy (/ ?y 2.0))
           (diagonal (vec-from-to ?ulhc ?lrhc))
           (mid (vec-add ?ulhc (vec-mul diagonal 0.5)))
           (mid-up (vec-add mid (vec-mul dy-vec (+ 1 ?dist))))
           (llhc (vec-add mid-up (vec-mul dx-vec (- dx))))
           (lrhc (vec-add mid-up (vec-mul dx-vec dx)))
           (ulhc (vec-add llhc (vec-mul dy-vec ?y)))
           (urhc (vec-add lrhc (vec-mul dy-vec ?y)))
           (region (map vec->ints (list ulhc urhc llhc lrhc))))
       (Claim ?p 'has-region (cons ?region region))))

(When ((?someone wishes (?p has-region-down (?region ?x ?y ?dist)))
       (?p (page points) (?ulhc ?urhc ?llhc ?lrhc)))
 do (let* ((dx-vec (vec-from-to ?ulhc ?urhc))
           (dy-vec (vec-from-to ?ulhc ?llhc))
           (dx (/ ?x 2.0)) (dy (/ ?y 2.0))
           (diagonal (vec-from-to ?ulhc ?lrhc))
           (mid (vec-add ?ulhc (vec-mul diagonal 0.5)))
           (mid-down (vec-add mid (vec-mul dy-vec (+ 1 ?dist))))
           (ulhc (vec-add mid-down (vec-mul dx-vec (- dx))))
           (urhc (vec-add mid-down (vec-mul dx-vec dx)))
           (llhc (vec-add ulhc (vec-mul dy-vec ?y)))
           (lrhc (vec-add urhc (vec-mul dy-vec ?y)))
           (region (map vec->ints (list ulhc urhc llhc lrhc))))
       (Claim ?p 'has-region (cons ?region region))))

; all calculations are done based on the detected upper left-hand corner
; using inner tag box vectors
(define (region-from-tag dx1 dy1 dx2 dy2 dx3 dy3 dx4 dy4 ulhc urhc llhc lrhc)
 (let* ((dx-vec (vec-from-to ulhc urhc))
        (dy-vec (vec-from-to ulhc llhc))
        (new-ulhc   (vec->ints (vec-add (vec-add ulhc (vec-mul dx-vec dx1))
                                                      (vec-mul dy-vec dy1))))
        (new-urhc   (vec->ints (vec-add (vec-add ulhc (vec-mul dx-vec dx2))
                                                      (vec-mul dy-vec dy2))))
        (new-llhc   (vec->ints (vec-add (vec-add ulhc (vec-mul dx-vec dx3))
                                                      (vec-mul dy-vec dy3))))
        (new-lrhc   (vec->ints (vec-add (vec-add ulhc (vec-mul dx-vec dx4))
                                                      (vec-mul dy-vec dy4)))))
    (list new-ulhc new-urhc new-llhc new-lrhc)))

(When ((?someone wishes (?p has-region-from-tag
  (?region ?dx1 ?dy1 ?dx2 ?dy2 ?dx3 ?dy3 ?dx4 ?dy4)))
       (?p (page points) (?ulhc ?urhc ?llhc ?lrhc)))
 do (let ((region (region-from-tag ?dx1 ?dy1 ?dx2 ?dy2 ?dx3 ?dy3 ?dx4 ?dy4
                                   ?ulhc ?urhc ?llhc ?lrhc)))
      (Claim ?p 'has-region (cons ?region region))))

; asserts the region adjusted for rotation:
; this is useful when drawing as if axis-aligned, then rotating back
(When ((?someone wishes (?p has-region-from-tag-unrotated
  (?region ?dx1 ?dy1 ?dx2 ?dy2 ?dx3 ?dy3 ?dx4 ?dy4)))
       (?p (page points) (?ulhc ?urhc ?llhc ?lrhc))
       (?p (page rotation) ?rotation)) ; clockwise rotation
 do (let* ((region (region-from-tag ?dx1 ?dy1 ?dx2 ?dy2 ?dx3 ?dy3 ?dx4 ?dy4
                                    ?ulhc ?urhc ?llhc ?lrhc))
           (ulhc (car region)) (urhc (cadr region))
           (llhc (caddr region)) (lrhc (cadddr region))
           (aabb-pts (rotate-rect ulhc urhc llhc lrhc ?rotation)))
        (Claim ?p 'has-region (cons ?region (cons ?rotation aabb-pts)))))
